# Generated by Django 4.1.7 on 2023-03-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_model'),
        ),
    ]
